package com.libertymutual.goforcode.blazebit.configuration;

import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.password.PasswordEncoder;

import com.libertymutual.goforcode.blazebit.models.Trail;
import com.libertymutual.goforcode.blazebit.models.User;
import com.libertymutual.goforcode.blazebit.models.UserTrail;
import com.libertymutual.goforcode.blazebit.repositories.TrailRepository;
import com.libertymutual.goforcode.blazebit.repositories.UserRepository;
import com.libertymutual.goforcode.blazebit.repositories.UserTrailRepository;

@Configuration
@Profile("development")
public class SeedData {

	public SeedData(UserRepository userRepo, TrailRepository trailRepo, UserTrailRepository userTrailRepo, PasswordEncoder encoder) {
		User user = new User("joshie", encoder.encode("password"));
		Trail trail = new Trail();
		
		trail = new Trail("Lingering Trail", 1d, 400); trailRepo.save(trail);
		trail = new Trail("Lundin Peak Trail", 1d, 700); trailRepo.save(trail);
		trail = new Trail("Adventure Trail", 1.4d, 300); trailRepo.save(trail);
		trail = new Trail("Fallsview Canyon (Falls View)", 1.5d, 300); trailRepo.save(trail);
		trail = new Trail("Section Line Trail", 1.6d, 2022); trailRepo.save(trail);
		trail = new Trail("Barlow Point", 2d, 3000); trailRepo.save(trail);
		trail = new Trail("Boardman Lake", 2d, 300); trailRepo.save(trail);
		trail = new Trail("Franklin Falls", 2d, 400); trailRepo.save(trail);
		trail = new Trail("High School Trail", 2d, 400); trailRepo.save(trail);
		trail = new Trail("Twin Falls", 2d, 500); trailRepo.save(trail);
		trail = new Trail("Crater Lake", 2d, 550); trailRepo.save(trail);
		trail = new Trail("Mirror Lake", 2d, 800); trailRepo.save(trail);
		trail = new Trail("Clear West Peak", 2d, 900); trailRepo.save(trail);
		trail = new Trail("Suntop Peak", 2d, 1100); trailRepo.save(trail);
		trail = new Trail("Chambers Bay Loop", 2.25d, 315); trailRepo.save(trail);
		trail = new Trail("Twanoh State Park", 2.3d, 375); trailRepo.save(trail);
		trail = new Trail("Old Robe Canyon", 2.4d, 350); trailRepo.save(trail);
		trail = new Trail("Mount Peak (Pinnacle Peak)", 2.4d, 1058); trailRepo.save(trail);
		trail = new Trail("Franklin Ghost Town", 2.5d, 300); trailRepo.save(trail);
		trail = new Trail("Coal Creek Falls", 2.5d, 350); trailRepo.save(trail);
		trail = new Trail("Guillemot Cove", 2.5d, 350); trailRepo.save(trail);
		trail = new Trail("Lunds Gulch", 2.5d, 425); trailRepo.save(trail);
		trail = new Trail("Boulder Garden Loop", 2.5d, 800); trailRepo.save(trail);
		trail = new Trail("Heybrook Lookout", 2.6d, 850); trailRepo.save(trail);
		trail = new Trail("Preston Railroad Grade", 2.6d, 900); trailRepo.save(trail);
		trail = new Trail("Index Town Wall", 2.6d, 1270); trailRepo.save(trail);
		trail = new Trail("Neiderprum Trail", 2.65d, 2400); trailRepo.save(trail);
		trail = new Trail("Evergreen Mountain Lookout", 2.8d, 1425); trailRepo.save(trail);
		trail = new Trail("Cable Line Trail", 3d, 2022); trailRepo.save(trail);
		trail = new Trail("Iverson Railroad Trail", 3d, 300); trailRepo.save(trail);
		trail = new Trail("Lodge Lake", 3d, 500); trailRepo.save(trail);
		trail = new Trail("Trout Creek", 3d, 500); trailRepo.save(trail);
		trail = new Trail("Cedar Butte", 3d, 900); trailRepo.save(trail);
		trail = new Trail("Lake Laura Backdoor", 3d, 1000); trailRepo.save(trail);
		trail = new Trail("Scout Patrol Peak", 3d, 2724); trailRepo.save(trail);
		trail = new Trail("Silver Gulch Trail", 3d, 1000); trailRepo.save(trail);
		trail = new Trail("Whittaker Wilderness Peak", 3d, 1228); trailRepo.save(trail);
		trail = new Trail("Mount Catherine", 3d, 1300); trailRepo.save(trail);
		trail = new Trail("Nordic Pass - Hyak", 3.2d, 660); trailRepo.save(trail);
		trail = new Trail("Gazzam Lake and Close Beach", 3.4d, 500); trailRepo.save(trail);
		trail = new Trail("Kelly Butte", 3.4d, 900); trailRepo.save(trail);
		trail = new Trail("Dosewallips State Park - Steam Donkey Trail", 3.5d, 400); trailRepo.save(trail);
		trail = new Trail("Poo Poo Point - Chirico Trail", 3.6d, 1700); trailRepo.save(trail);
		trail = new Trail("Talus Loop", 3.7d, 1750); trailRepo.save(trail);
		trail = new Trail("Pinnacle Lake", 3.8d, 1100); trailRepo.save(trail);
		trail = new Trail("Wildside Trail-De Leo Wall", 4d, 350); trailRepo.save(trail);
		trail = new Trail("CCC Road: Upper Trailhead", 4d, 400); trailRepo.save(trail);
		trail = new Trail("Lower Gold Creek Basin Snowshoe", 4d, 400); trailRepo.save(trail);
		trail = new Trail("Tradition Lake Loop", 4d, 400); trailRepo.save(trail);
		trail = new Trail("Twin Lakes Snowshoe", 4d, 400); trailRepo.save(trail);
		trail = new Trail("Elk Lake", 4d, 500); trailRepo.save(trail);
		trail = new Trail("Lake Constance", 4d, 3300); trailRepo.save(trail);
		trail = new Trail("Taylor Mountain", 4d, 550); trailRepo.save(trail);
		trail = new Trail("Tiger Mountain Trail South", 4d, 600); trailRepo.save(trail);
		trail = new Trail("Mount Persis", 4d, 2658); trailRepo.save(trail);
		trail = new Trail("Mine Road Trail", 4d, 650); trailRepo.save(trail);
		trail = new Trail("Denny Creek", 4d, 700); trailRepo.save(trail);
		trail = new Trail("Bridal Veil Falls", 4d, 1000); trailRepo.save(trail);
		trail = new Trail("Gold Mountain", 4d, 1087); trailRepo.save(trail);
		trail = new Trail("Rattlesnake Ledge", 4d, 1160); trailRepo.save(trail);
		trail = new Trail("Wilderness Peak", 4d, 1200); trailRepo.save(trail);
		trail = new Trail("Eagle Lake", 4d, 1500); trailRepo.save(trail);
		trail = new Trail("Glacier Basin", 4.23d, 2159); trailRepo.save(trail);
		trail = new Trail("Big Creek", 4.5d, 900); trailRepo.save(trail);
		trail = new Trail("Heather Lake", 4.6d, 1100); trailRepo.save(trail);
		trail = new Trail("Heather Lake Snowshoe", 4.6d, 1100); trailRepo.save(trail);
		trail = new Trail("Bootleg Trail", 4.6d, 1300); trailRepo.save(trail);
		trail = new Trail("Mount Zion", 4.6d, 1300); trailRepo.save(trail);
		trail = new Trail("West Defiance - Putrid Pete's Peak", 4.8d, 3020); trailRepo.save(trail);
		trail = new Trail("Miller Peninsula-Thompson Spit", 5d, 360); trailRepo.save(trail);
		trail = new Trail("Eagle Lake Fisherman's Trail", 5d, 400); trailRepo.save(trail);
		trail = new Trail("Cherry Creek Falls", 5d, 450); trailRepo.save(trail);
		trail = new Trail("Granite Mountain Snowshoe", 5d, 3750); trailRepo.save(trail);
		trail = new Trail("Green Mountain 2", 5d, 1000); trailRepo.save(trail);
		trail = new Trail("Source Lake Snowshoe", 5d, 1000); trailRepo.save(trail);
		trail = new Trail("Tiger Mountain Trail North", 5d, 1100); trailRepo.save(trail);
		trail = new Trail("Lake Twentytwo / Lake 22 Snowshoe", 5d, 1200); trailRepo.save(trail);
		trail = new Trail("Little Si", 5d, 1200); trailRepo.save(trail);
		trail = new Trail("Mount Walker", 5d, 2000); trailRepo.save(trail);
		trail = new Trail("Summit Lake", 5d, 1200); trailRepo.save(trail);
		trail = new Trail("Lena Lake", 5d, 1300); trailRepo.save(trail);
		trail = new Trail("Peek-a-boo Lake", 5d, 1500); trailRepo.save(trail);
		trail = new Trail("Lake Twentytwo - Lake 22", 5.4d, 1350); trailRepo.save(trail);
		trail = new Trail("West Tiger 3", 5d, 2100); trailRepo.save(trail);
		trail = new Trail("Bedal Basin", 5.2d, 1900); trailRepo.save(trail);
		trail = new Trail("Eight Mile - Squire Creek Pass", 5.4d, 2350); trailRepo.save(trail);
		trail = new Trail("Ashland Lakes", 5.5d, 800); trailRepo.save(trail);
		trail = new Trail("Mount Pilchuck", 5.4d, 2200); trailRepo.save(trail);
		trail = new Trail("Wallace Falls", 5.5d, 1200); trailRepo.save(trail);
		trail = new Trail("Coal Creek Trail", 6d, 550); trailRepo.save(trail);
		trail = new Trail("Anti-Aircraft Peak", 6d, 625); trailRepo.save(trail);
		trail = new Trail("Bearhead Mountain", 6d, 1640); trailRepo.save(trail);
		trail = new Trail("Cave Ridge - Guye Peak", 6d, 2100); trailRepo.save(trail);
		trail = new Trail("Iron Goat Trail", 6d, 700); trailRepo.save(trail);
		trail = new Trail("Source Lake", 6d, 700); trailRepo.save(trail);
		trail = new Trail("Ira Spring Trail - Mason Lake", 6d, 2550); trailRepo.save(trail);
		trail = new Trail("Coal Creek Snowshoe", 6d, 900); trailRepo.save(trail);
		trail = new Trail("Low Mountain", 6d, 3300); trailRepo.save(trail);
		trail = new Trail("Mailbox Peak", 6d, 3821); trailRepo.save(trail);
		trail = new Trail("Margaret Lake", 6d, 1800); trailRepo.save(trail);
		trail = new Trail("Mount Sawyer", 6d, 1200); trailRepo.save(trail);
		trail = new Trail("Snoqualmie Mountain", 6d, 3100); trailRepo.save(trail);
		trail = new Trail("Tonga Ridge / Mount Sawyer", 6d, 1200); trailRepo.save(trail);
		trail = new Trail("Dirty Harry's Balcony", 6d, 1300); trailRepo.save(trail);
		trail = new Trail("Teneriffe Falls (Kamikaze Falls)", 6d, 1420); trailRepo.save(trail);
		trail = new Trail("Mount Ellinor", 6.2d, 3200); trailRepo.save(trail);
		trail = new Trail("Talapus and Olallie Lakes", 6.2d, 1220); trailRepo.save(trail);
		trail = new Trail("Keechelus Ridge Snowshoe", 6.4d, 2100); trailRepo.save(trail);
		trail = new Trail("Snow Lake", 6.4d, 1000); trailRepo.save(trail);
		trail = new Trail("East Tiger - Silent Swamp", 6.6d, 450); trailRepo.save(trail);
		trail = new Trail("Squak Mountain", 6.6d, 1684); trailRepo.save(trail);
		trail = new Trail("Cutthroat Lakes", 6.8d, 2600); trailRepo.save(trail);
		trail = new Trail("Upper Dungeness River", 6.8d, 600); trailRepo.save(trail);
		trail = new Trail("CCC Road: Blowout Creek Trailhead", 7d, 620); trailRepo.save(trail);
		trail = new Trail("Headlee Pass and Vesper Lake", 7d, 2600); trailRepo.save(trail);
		trail = new Trail("Independence and North Lakes", 7d, 2200); trailRepo.save(trail);
		trail = new Trail("Lime Kiln Trail", 7d, 625); trailRepo.save(trail);
		trail = new Trail("Little Bandera Mountain", 7d, 2850); trailRepo.save(trail);
		trail = new Trail("Little Saint Helens", 7d, 1200); trailRepo.save(trail);
		trail = new Trail("Phils Trail - Thrush Gap Loop", 7d, 1606); trailRepo.save(trail);
		trail = new Trail("Rainy Lake", 7d, 2700); trailRepo.save(trail);
		trail = new Trail("Tonga Ridge Snowshoe", 7d, 1400); trailRepo.save(trail);
		trail = new Trail("Lake Serene - Bridal Veil Falls", 7.2d, 2000); trailRepo.save(trail);
		trail = new Trail("Beckler Peak", 7.4d, 2263); trailRepo.save(trail);
		trail = new Trail("Miller River Road", 7.4d, 700); trailRepo.save(trail);
		trail = new Trail("Mount Si - Old Trail", 7.4d, 3420); trailRepo.save(trail);
		trail = new Trail("Poo Poo Point", 7.4d, 1650); trailRepo.save(trail);
		trail = new Trail("Annette Lake", 7.5d, 1400); trailRepo.save(trail);
		trail = new Trail("Blanca Lake", 7.5d, 3300); trailRepo.save(trail);
		trail = new Trail("Dirty Face Ridge", 7.5d, 3000); trailRepo.save(trail);
		trail = new Trail("Bandera Mountain", 7.6d, 3000); trailRepo.save(trail);
		trail = new Trail("Deadfall", 7.6d, 2240); trailRepo.save(trail);
		trail = new Trail("West Tiger 2", 7.8d, 2300); trailRepo.save(trail);
		trail = new Trail("Amabilis Mountain Snowshoe", 8d, 2100); trailRepo.save(trail);
		trail = new Trail("Bare Mountain", 8d, 3250); trailRepo.save(trail);
		trail = new Trail("CCC Road: Lower Trailhead", 8d, 550); trailRepo.save(trail);
		trail = new Trail("Florence Peak", 8d, 3700); trailRepo.save(trail);
		trail = new Trail("Granite Mountain", 8d, 3800); trailRepo.save(trail);
		trail = new Trail("Monte Cristo Ghost Town", 8d, 700); trailRepo.save(trail);
		trail = new Trail("Jumpoff Ridge", 8d, 1800); trailRepo.save(trail);
		trail = new Trail("Lake of the Angels", 8d, 3400); trailRepo.save(trail);
		trail = new Trail("Harris Lake Trail", 8d, 1300); trailRepo.save(trail);
		trail = new Trail("Mount Si", 8d, 3150); trailRepo.save(trail);
		trail = new Trail("Pratt Lake Basin", 8d, 2300); trailRepo.save(trail);
		trail = new Trail("Rachel Lake", 8d, 1600); trailRepo.save(trail);
		trail = new Trail("Rooster Mountain", 8d, 4100); trailRepo.save(trail);
		trail = new Trail("Squak Mountain's East Side Loop", 8d, 1700); trailRepo.save(trail);
		trail = new Trail("Tinkham and Silver Peaks", 8d, 2600); trailRepo.save(trail);
		trail = new Trail("Mount Townsend", 8.2d, 2900); trailRepo.save(trail);
		trail = new Trail("Wallace Lake - Greg Ball Trail", 8.2d, 1500); trailRepo.save(trail);
		trail = new Trail("Lower Gray Wolf River", 8.4d, 800); trailRepo.save(trail);
		trail = new Trail("West Fork Dosewallips River", 8.4d, 900); trailRepo.save(trail);
		trail = new Trail("Quartz Creek", 8.4d, 1500); trailRepo.save(trail);
		trail = new Trail("Avalanche Mountain", 8.5d, 3000); trailRepo.save(trail);
		trail = new Trail("Mount Washington", 8.5d, 3250); trailRepo.save(trail);
		trail = new Trail("Squire Creek", 8.5d, 2566); trailRepo.save(trail);
		trail = new Trail("Talapus Lake Snowshoe", 8.5d, 1600); trailRepo.save(trail);
		trail = new Trail("Tunnel Creek", 8.5d, 2500); trailRepo.save(trail);
		trail = new Trail("Boulder River", 8.6d, 700); trailRepo.save(trail);
		trail = new Trail("Greider Lakes", 8.6d, 1370); trailRepo.save(trail);
		trail = new Trail("Mount Dickerman", 8.6d, 3875); trailRepo.save(trail);
		trail = new Trail("Baldy", 9d, 3700); trailRepo.save(trail);
		trail = new Trail("Dog Mountain (North Fork Snoqualmie)", 9d, 3800); trailRepo.save(trail);
		trail = new Trail("Gothic Basin", 9d, 2840); trailRepo.save(trail);
		trail = new Trail("Iron Horse Trail: Washington Creek", 9d, 300); trailRepo.save(trail);
		trail = new Trail("Johnson Ridge", 9d, 2650); trailRepo.save(trail);
		trail = new Trail("Kendall Peak Lakes Snowshoe", 9d, 1700); trailRepo.save(trail);
		trail = new Trail("McClellan Butte", 9d, 3700); trailRepo.save(trail);
		trail = new Trail("Melakwa Lake", 9d, 2300); trailRepo.save(trail);
		trail = new Trail("Wildcat Trail", 9d, 1000); trailRepo.save(trail);
		trail = new Trail("Mildred Lakes", 9d, 2300); trailRepo.save(trail);
		trail = new Trail("Mount Higgins", 9d, 3400); trailRepo.save(trail);
		trail = new Trail("Mount Margaret Snowshoe", 9d, 2800); trailRepo.save(trail);
		trail = new Trail("Mount Si via Mount Teneriffe Road Trail", 9d, 2950); trailRepo.save(trail);
		trail = new Trail("Middle Tiger", 9d, 1127); trailRepo.save(trail);
		trail = new Trail("Vesper Peak", 9d, 4100); trailRepo.save(trail);
		trail = new Trail("Welch Peaks", 9d, 3300); trailRepo.save(trail);
		trail = new Trail("Twin Lakes and Lake Lillian", 9d, 1500); trailRepo.save(trail);
		trail = new Trail("Windy Pass - Mount Catherine Snowshoe", 9d, 2300); trailRepo.save(trail);
		trail = new Trail("Green Lake", 9.2d, 1300); trailRepo.save(trail);
		trail = new Trail("Commonwealth Basin", 10d, 2700); trailRepo.save(trail);
		trail = new Trail("Commonwealth Basin Snowshoe", 10d, 2300); trailRepo.save(trail);
		trail = new Trail("Deer Creek Road - Kelcema Lake Snowshoe", 10d, 1600); trailRepo.save(trail);
		trail = new Trail("Elbo Creek", 10d, 1910); trailRepo.save(trail);
		trail = new Trail("Otter Falls - Taylor River", 10d, 650); trailRepo.save(trail);
		trail = new Trail("Green Mountain", 10d, 3600); trailRepo.save(trail);
		trail = new Trail("Island Lake - Rainbow Lake", 10d, 2000); trailRepo.save(trail);
		trail = new Trail("Lena Lake - Valley of Silent Men Snowshoe", 10d, 2000); trailRepo.save(trail);
		trail = new Trail("Lower Big Quilcene River", 10d, 800); trailRepo.save(trail);
		trail = new Trail("Mallardy Ridge Snowshoe", 10d, 1900); trailRepo.save(trail);
		trail = new Trail("North Fork Skykomish River", 10d, 1000); trailRepo.save(trail);
		trail = new Trail("Fisher Lake", 10d, 1350); trailRepo.save(trail);
		trail = new Trail("Mowich Lake Snowshoe", 10d, 1400); trailRepo.save(trail);
		trail = new Trail("Snow Lake Snowshoe", 10d, 2000); trailRepo.save(trail);
		trail = new Trail("Walt Bailey Trail - Bald Mountain", 10d, 2300); trailRepo.save(trail);
		trail = new Trail("West Tiger 1", 10d, 1600); trailRepo.save(trail);
		trail = new Trail("West Tiger Railroad Grade", 10d, 1600); trailRepo.save(trail);
		trail = new Trail("Goat Lake", 10.4d, 1400); trailRepo.save(trail);
		trail = new Trail("Duckabush River", 10.6d, 2300); trailRepo.save(trail);
		trail = new Trail("East Tiger", 10.6d, 2940); trailRepo.save(trail);
		trail = new Trail("Marmot Pass - Upper Big Quilcene", 10.6d, 3500); trailRepo.save(trail);
		trail = new Trail("Rattlesnake Mountain", 10.9d, 2520); trailRepo.save(trail);
		trail = new Trail("Deception Creek", 11d, 1200); trailRepo.save(trail);
		trail = new Trail("Dingford Creek-Hester Lake", 11d, 2600); trailRepo.save(trail);
		trail = new Trail("Dingford Creek-Myrtle Lake", 11d, 2600); trailRepo.save(trail);
		trail = new Trail("Elliott Creek", 11d, 1300); trailRepo.save(trail);
		trail = new Trail("Gold Creek-Alaska Lake", 11d, 1600); trailRepo.save(trail);
		trail = new Trail("Kendall Katwalk", 11d, 2700); trailRepo.save(trail);
		trail = new Trail("Mount Defiance", 11d, 3384); trailRepo.save(trail);
		trail = new Trail("Mount Pilchuck Snowshoe", 11d, 2600); trailRepo.save(trail);
		trail = new Trail("Perry Creek", 11d, 3400); trailRepo.save(trail);
		trail = new Trail("Rock Creek Falls", 11d, 2100); trailRepo.save(trail);
		trail = new Trail("Silver Lake - Monte Cristo", 11d, 2000); trailRepo.save(trail);
		trail = new Trail("Silver Lakes", 11d, 3400); trailRepo.save(trail);
		trail = new Trail("Surprise and Glacier Lakes", 11d, 2700); trailRepo.save(trail);
		trail = new Trail("Lake Dorothy - Lake Bear - Lake Deer", 11.5d, 1550); trailRepo.save(trail);
		trail = new Trail("Boardman Lake Snowshoe", 11.9d, 1800); trailRepo.save(trail);
		trail = new Trail("Alaska Lake Snowshoe", 12d, 1600); trailRepo.save(trail);
		trail = new Trail("McDonald Mountain", 12d, 3500); trailRepo.save(trail);
		trail = new Trail("Mount Gardner", 12d, 1500); trailRepo.save(trail);
		trail = new Trail("Sunnybrook Meadows", 12d, 4000); trailRepo.save(trail);
		trail = new Trail("Tin Can Gap", 12d, 2800); trailRepo.save(trail);
		trail = new Trail("Tubal Cain Mine and Buckhorn Lake", 12d, 2000); trailRepo.save(trail);
		trail = new Trail("Lower Dungeness River", 12.6d, 1000); trailRepo.save(trail);
		trail = new Trail("Bessemer Mountain", 13d, 4100); trailRepo.save(trail);
		trail = new Trail("Fortune Ponds", 13d, 2700); trailRepo.save(trail);
		trail = new Trail("West Fork Foss River and Lakes", 13d, 3700); trailRepo.save(trail);
		trail = new Trail("Mount Price", 13.5d, 4500); trailRepo.save(trail);
		trail = new Trail("Mount Townsend Snowshoe", 13.5d, 2500); trailRepo.save(trail);
		trail = new Trail("East Fork Foss River Snowshoe", 13.6d, 1200); trailRepo.save(trail);
		trail = new Trail("Boulder Lake", 13.8d, 2140); trailRepo.save(trail);
		trail = new Trail("Grand Ridge Park", 14d, 1100); trailRepo.save(trail);
		trail = new Trail("Mount Forgotten", 14d, 4200); trailRepo.save(trail);
		trail = new Trail("Mount Teneriffe Road Trail", 14d, 3800); trailRepo.save(trail);
		trail = new Trail("Mount Townsend Backdoor", 14d, 3200); trailRepo.save(trail);
		trail = new Trail("Royal Basin", 14d, 2650); trailRepo.save(trail);
		trail = new Trail("Upper Lena Lake", 14d, 3900); trailRepo.save(trail);
		trail = new Trail("Upper Middle Fork Snoqualmie Meadow", 14d, 1600); trailRepo.save(trail);
		trail = new Trail("West Cady Ridge to Benchmark Mountain", 14.4d, 3700); trailRepo.save(trail);
		trail = new Trail("Deep Lake", 14.5d, 2150); trailRepo.save(trail);
		trail = new Trail("Three Fingers", 15d, 4200); trailRepo.save(trail);
		trail = new Trail("Joe Lake", 16d, 2235); trailRepo.save(trail);
		trail = new Trail("Tiger Mountain Trail", 16d, 2200); trailRepo.save(trail);
		trail = new Trail("Snoqualmie Lake", 17d, 1900); trailRepo.save(trail);
		trail = new Trail("East Fork Foss - Necklace Valley", 18d, 3400); trailRepo.save(trail);
		trail = new Trail("Spectacle Lake", 22d, 1500); trailRepo.save(trail);
		
		UserTrail userTrail = new UserTrail();
		
		userRepo.save(user);
		trailRepo.save(trail);
		userTrail.setUser(user);
		userTrail.setTrail(trail);
		userRepo.save(user);
		trailRepo.save(trail);
		userTrailRepo.save(userTrail);
	}
}
